DROP TABLE IF EXISTS `entries`;
CREATE TABLE `entries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `stock_arrival_date` datetime NOT NULL,
  `brands` varchar(100) DEFAULT NULL,
  `sheet_no` int(11) DEFAULT NULL,
  `no_of_sku` int(11) DEFAULT NULL,
  `content_asignee` varchar(50) DEFAULT NULL,
  `content_assign_date` datetime DEFAULT NULL,
  `catalog_name` varchar(50) DEFAULT NULL,
  `catalog_submission_date` datetime DEFAULT NULL,
  `photo_complete_date` datetime DEFAULT NULL,
  `no_of_images` int(11) DEFAULT NULL,
  `editing_assigned_to` varchar(50) DEFAULT NULL,
  `raw_image_location` varchar(100) DEFAULT NULL,
  `image_assignment_date` datetime DEFAULT NULL,
  `editing_completion_date` datetime DEFAULT NULL,
  `edited_image_path` varchar(100) DEFAULT NULL,
  `approved_image_path` varchar(100) DEFAULT NULL,
  `approved_images` int(11) DEFAULT NULL,
  `approved_date` datetime DEFAULT NULL,
  `rating` int(11) DEFAULT NULL,
  `launch_complete` tinyint(1) DEFAULT 0,
  `launch_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1 ;
