create table entries(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  stock_arrival_date DATETIME NOT NULL,
  brands VARCHAR(100),
  sheet_no INT,
  no_of_sku INT,
  content_asignee VARCHAR(50),
  content_assign_date DATETIME,
  catalog_name VARCHAR(50),
  catalog_submission_date DATETIME,
  photo_complete_date DATETIME,
  no_of_images INT,
  editing_assigned_to VARCHAR(50),
  raw_image_location VARCHAR(100),
  image_assignment_date DATETIME,
  editing_completion_date DATETIME,
  edited_image_path VARCHAR(100),
  approved_image_path VARCHAR(100),
  approved_images INT,
  approved_date DATETIME,
  rating INT,
  launch_complete TINYINT(1),
  launch_date DATETIME
)type=innodb
